### PR TITLE
Updating emoji list to match user story

### PR DESCRIPTION
**Pull request by sfkiwi**

### CODE REVIEW

**Comment by sfkiwi** [comment]
[As a user I want to add my current emotion to my new topic](https://trello.com/c/aRGlARZM/30-as-a-user-i-want-to-add-my-current-emotion-to-my-new-topic)

**Comment by sfkiwi** [comment]
[Create icons to represent each emotion](https://trello.com/c/k7Mmk8W8/55-create-icons-to-represent-each-emotion)

**Comment by sfkiwi** [comment]
[Create selection component containing list of emotions](https://trello.com/c/Rp9TGSMi/54-create-selection-component-containing-list-of-emotions)

**Review by jrod1032 — APPROVED** [review]
Looks good!

**Pull request merged**
