### PR TITLE
Adding user avatars plus some small styling fixes

### PR DESCRIPTION
**Pull request by sfkiwi**

### CODE REVIEW

**Comment by sfkiwi** [comment]
[As a user I want to see that i’m logged in](https://trello.com/c/zODmoHbt/183-as-a-user-i-want-to-see-that-im-logged-in)

**Comment by sfkiwi** [comment]
[Move logout button to user name drop down list](https://trello.com/c/Q0YNuIav/185-move-logout-button-to-user-name-drop-down-list)

**Comment by sfkiwi** [comment]
[Add user profile pic and name to top nav](https://trello.com/c/gmxSGhRa/184-add-user-profile-pic-and-name-to-top-nav)

**Review by stphnchoe — APPROVED** [review]
Nice. Refactored code, resolved issues, and increased app appeal with an image.

**Pull request merged**
